정윤서 과제 제출합니다. (Tag 구현)
wafflestudio/seminar-2022-django-assignment2 pull request #3
Opened 2022-10-31 16:51 UTC by yoonsuhchung

1. Tag를 구현하긴 했는데 각 post나 comment가 임의의 개수의 tag를 가지도록 하는 방법(manytomany)을 생각하기 어려워 manytoone으로 구현하였습니다.

2. Comment에서 detail은 없다는 스펙에 따라 특정 클래스들만을 상속하여 update와 delete만을 구현하였는데, RetrieveUpdateDestroyAPIView를 상속받을 때와는 달리 기존의 메소드들을 override하지 않으면 not allowed method가 떠서 구현해야 하는 메소드들을 override하게 되었습니다. (그 이유가 떠오르지 않네요..)

2022-11-08 06:11 UTC, narayo9 requested changes
전반적으로 django layer를 잘 활용해주시고 knox도 추가하신 부분이 눈에 띄네요 🙌🏼 

고생하셨습니다!!

2022-11-08 06:11 UTC, chanuk-kim commented on MediumProject/blog/models.py
> +    content = models.CharField(max_length=10, primary_key=True, blank=True, default="none")
manytomany로 가기 어려우셨다는 게 아쉽네요 😢  어떤 부분이었을까요?

Tag가 두 가지 모델로 나뉘게 되면 추후 db layer에서 filter / sort하기 어렵습니다.

2022-11-08 06:11 UTC, chanuk-kim commented on MediumProject/blog/views.py
> +
LoginView 같은 경우는 model을 crud하는 일반적인 case에서 벗어나므로 APIView를 사용했으면 더 좋았을 것 같아요.

2022-11-08 06:11 UTC, chanuk-kim commented on MediumProject/blog/views.py
> +        raise PermissionDenied(message)
요 뷰와 다른 뷰에서 permission_denied를 상속하셨는데, 이유가 있을까요?

2022-11-08 06:11 UTC, chanuk-kim commented on MediumProject/blog/views.py
> +        print(request.user)
print는 제거해주시는 게 좋아요!

2022-11-08 06:11 UTC, chanuk-kim commented on MediumProject/blog/views.py
> +    permission_classes = [IsCreatorOrReadOnly | IsAdminUser]
&나 ,가 아닌 |로 결합하면 둘 중 하나만 통과되면 된다는 뜻이어서, 문제가 될만한 부분이 있을 것 같아요.

2022-11-08 06:11 UTC, narayo9 commented on MediumProject/blog/views.py
> +        super().check_object_permissions(request, obj)
요 부분은 제거해야겠네요!

2022-11-08 06:11 UTC, narayo9 commented on MediumProject/blog/views.py
> +        return self.destroy(request, *args, **kwargs)
요기는 테스트용으로 남아있는 코드일까요?

2022-11-08 06:11 UTC, narayo9 commented on MediumProject/blog/views.py
> +        return self.destroy(request, *args, **kwargs)
아 요기가 질문 2 부분이군요. mixin이 아닌 Views를 상속하셔서 생기는 문제인 것 같습니다. 

요런 식으로 수정하시면 의도한 바대로 수정하실 수 있을 것 같아요~

```suggestion python
class CommentRetrieveUpdateDestroyView(UpdateModelMixin, DestroyModelMixin, GenericAPIView):
```

2022-11-08 08:18 UTC, yoonsuhchung commented on MediumProject/blog/views.py
> +        raise PermissionDenied(message)
왜 그런진 모르겠는데 이렇게 하지 않았을 때는 제가 원하는 메시지가 에러메시지로 뜨지 않아서 한 번 시도해 보았습니다..!!

2022-11-08 08:24 UTC, yoonsuhchung commented on MediumProject/blog/models.py
> +    content = models.CharField(max_length=10, primary_key=True, blank=True, default="none")
-post나 comment를 생성할 때 임의의 개수의 tag를 생성할 수 있도록 하는 것이 자연스러울 것 같았는데 임의의 개수의 field를 받게 되면 deserialize 과정에서 어떻게 manytomanyfield로 연결해줄지 생각이 잘 나지 않았습니다..ㅠㅠ
-이 부분은 처음에 하나로 구현하였다가 view가 분리되어 있는 것 같길래 편의상 나눴는데 좋지 않은 선택이었군요:/

2022-11-08 08:34 UTC, yoonsuhchung commented on MediumProject/blog/views.py
> +        return self.destroy(request, *args, **kwargs)
제가 처음에 이런 방식으로 했었는데 요청을 보내니 put, patch, delete Method가 다 허용되지 않은 method라고 떴습니다..! 문제의 원인을 찾을 수가 없어 일단 위와 같이 해결했습니다 :/

2022-11-13 14:54 UTC, mathema123 reviewed
구현하시느라 수고 많으셨습니다! 워낙 잘 구현하시기도 했고 찬욱님 코멘트도 있어서, 제 코멘트가 작게나마 도움이 되면 좋겠습니다. 제가 봤을 때는 전체적으로 SOLID 원칙에 입각해서 잘 구현하신 것 같습니다. 특히 Serializer의 세세한 구현을 통해 Fat view를 방지한 점이 좋게 느껴졌습니다.

2022-11-13 14:54 UTC, mathema123 commented on MediumProject/blog/views.py
> +        return PostListSerializer
제가 의도를 제대로 이해하지 못한 거 같은데, 두 가지 Serializer를 쓴 이유가 있을까요? View 별로 독립적인 Serializer를 사용하는 것도 괜찮을 것 같습니다.

2022-11-13 14:54 UTC, mathema123 commented on MediumProject/blog/serializers.py
> +        return res
300자 제한 조건을 Serializer에서 구현해 View의 기능과 분리한 것이 좋은 것 같습니다.

2022-11-13 14:54 UTC, mathema123 commented on MediumProject/blog/views.py
> +        return self.destroy(request, *args, **kwargs)
저도 이 부분은 찬욱님이 말씀하신 것처럼 수정되면 좋을 것 같습니다.

2023-03-22 16:25 UTC, closed without merging